// شحن تطبيقات وألعاب — قائمة الأقسام والعناصر (الطلب عبر واتساب حصرًا · الدفع USDT)
import { whatsappLink } from './format'

export const TOPUP_CATEGORIES = [
  { slug: 'games', name: 'ألعاب', emoji: '🎮' },
  { slug: 'social', name: 'تواصل اجتماعي', emoji: '💬' },
  { slug: 'apps', name: 'تطبيقات ومنصات', emoji: '📲' },
]

// [name, emoji]
export const TOPUP_ITEMS = {
  games: [
    ['شدات ببجي موبايل — PUBG UC', '🪂'],
    ['جواهر فري فاير — Free Fire', '💎'],
    ['جواهر فري فاير ماكس', '💠'],
    ['شدات كول أوف ديوتي موبايل — CODM', '🎖️'],
    ['ألماس موبايل ليجندز', '⚔️'],
    ['روبوكس — Robux', '🟥'],
    ['بطاقة Roblox هدية', '🎁'],
    ['كريستالات Genshin Impact', '🌟'],
    ['عملات Honkai Star Rail', '🚄'],
    ['عملات Wuthering Waves', '🌊'],
    ['عملات Zenless Zone Zero', '🌀'],
    ['جيمز Clash of Clans', '🏰'],
    ['جيمز Clash Royale', '🃏'],
    ['جيمز Brawl Stars', '⭐'],
    ['نقاط Valorant', '🔫'],
    ['RP — League of Legends', '🧙'],
    ['Wild Cores — Wild Rift', '📱'],
    ['V-Bucks — Fortnite', '🪓'],
    ['عملات Apex Legends', '🎯'],
    ['نقاط EA FC Mobile', '⚽'],
    ['كوينز eFootball', '🥅'],
    ['كوينز 8 Ball Pool', '🎱'],
    ['سبينات Coin Master', '🎰'],
    ['جيمز Stumble Guys', '🏃'],
    ['شحن Midasbuy عام', '🛡️'],
    ['محفظة Razer Gold', '🟩'],
    ['محفظة Steam', '🎮'],
    ['عملات Farlight 84', '🚀'],
    ['جيمز Hay Day', '🌾'],
    ['عملات PUBG New State', '🔭'],
  ],
  social: [
    ['عملات تيك توك — TikTok Coins', '🎵'],
    ['متابعين تيك توك', '📈'],
    ['مشاهدات تيك توك', '👀'],
    ['لايكات تيك توك', '❤️'],
    ['متابعين انستغرام', '📸'],
    ['لايكات انستغرام', '👍'],
    ['مشاهدات ريلز', '🎬'],
    ['متابعين فيسبوك', '📘'],
    ['لايكات ومشاركات فيسبوك', '🔗'],
    ['متابعين X (تويتر)', '🐦'],
    ['مشتركين يوتيوب', '▶️'],
    ['مشاهدات يوتيوب', '👁️'],
    ['ساعات مشاهدة يوتيوب', '⏱️'],
    ['أعضاء تيليجرام', '📨'],
    ['نجوم تيليجرام — Telegram Stars', '⭐'],
    ['تيليجرام بريميوم', '💠'],
    ['مشاهدات قنوات تيليجرام', '📡'],
    ['ألماس Bigo Live', '💎'],
    ['ألماس Likee', '💜'],
    ['عملات سناب شات — Snapchat', '👻'],
    ['ألماس Imo', '🗨️'],
    ['جواهر يلا لودو — Yalla Ludo', '🎲'],
  ],
  apps: [
    ['بطاقة iTunes / Apple', '🍎'],
    ['بطاقة iTunes أمريكية', '🇺🇸'],
    ['بطاقة Google Play', '🤖'],
    ['بطاقة Google Play أمريكية', '🌎'],
    ['بطاقة PlayStation Store', '🎮'],
    ['بطاقة Xbox', '🟢'],
    ['بطاقة Nintendo eShop', '🍄'],
    ['بطاقة Amazon', '📦'],
    ['اشتراك Netflix', '🎬'],
    ['اشتراك Shahid VIP', '📺'],
    ['اشتراك Anghami Plus', '🎧'],
    ['اشتراك Spotify Premium', '🎶'],
    ['اشتراك Deezer', '🎵'],
    ['اشتراك StarzPlay', '⭐'],
    ['اشتراك OSN+', '📺'],
    ['اشتراك YouTube Premium', '🔴'],
    ['اشتراك ChatGPT Plus', '🤖'],
    ['اشتراك Canva Pro', '🎨'],
    ['اشتراك CapCut Pro', '✂️'],
    ['اشتراك LinkedIn Premium', '💼'],
    ['اشتراك Zoom Pro', '📹'],
    ['مفتاح Windows 11 Pro', '🪟'],
    ['مفتاح Windows 10 Pro', '💻'],
    ['مفتاح Office 365', '📊'],
    ['شحن Binance — تحويل داخلي', '🟡'],
    ['شحن OKX — تحويل داخلي', '⬛'],
    ['شحن Bybit — تحويل داخلي', '🟠'],
    ['شراء / بيع USDT', '💵'],
  ],
}

export const TOPUP_COUNT = Object.values(TOPUP_ITEMS).reduce((s, list) => s + list.length, 0)

export const topupOrderLink = (name) =>
  whatsappLink(`مرحبًا 👋\nأرغب بطلب شحن:\n🎮 ${name}\n\nالكمية / المبلغ: \nطريقة الدفع: USDT 💰`)
