
with cat as (select id from public.categories where slug='audio')
insert into public.products (slug, name, brand, category_id, condition, network, price, old_price, stock, description, specs, main_image) values
('s2-apple-airpods-4-anc', 'سماعة Apple AirPods 4 مع ANC', 'Apple', (select id from cat), 'new', '4G', 149, null, 10, 'سماعة Apple AirPods 4 مع ANC — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 30 ساعة","colors":"أبيض"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp'),
('s2-airpods-max-usb-c', 'سماعة AirPods Max USB-C', 'Apple', (select id from cat), 'new', '4G', 529, null, 15, 'سماعة AirPods Max USB-C — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 24 ساعة","colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp'),
('s2-samsung-galaxy-buds3-pro', 'سماعة Samsung Galaxy Buds3 Pro', 'Samsung', (select id from cat), 'new', '4G', 189, null, 20, 'سماعة Samsung Galaxy Buds3 Pro — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 12 ساعة","colors":"رمادي"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp'),
('s2-samsung-galaxy-buds3', 'سماعة Samsung Galaxy Buds3', 'Samsung', (select id from cat), 'new', '4G', 149, null, 25, 'سماعة Samsung Galaxy Buds3 — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 40 ساعة","colors":"أبيض"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp'),
('s2-samsung-galaxy-buds-fe', 'سماعة Samsung Galaxy Buds FE', 'Samsung', (select id from cat), 'new', '4G', 79, null, 30, 'سماعة Samsung Galaxy Buds FE — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 30 ساعة","colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp'),
('s2-sony-wh-ch720n', 'سماعة Sony WH-CH720N لاسلكية', 'Sony', (select id from cat), 'new', '4G', 129, null, 10, 'سماعة Sony WH-CH720N لاسلكية — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 24 ساعة","colors":"رمادي"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp'),
('s2-sony-wf-c700n', 'سماعة Sony WF-C700N', 'Sony', (select id from cat), 'new', '4G', 89, null, 15, 'سماعة Sony WF-C700N — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 12 ساعة","colors":"أبيض"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp'),
('s2-jbl-tune-720bt', 'سماعة JBL Tune 720BT', 'JBL', (select id from cat), 'new', '4G', 59, null, 20, 'سماعة JBL Tune 720BT — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 40 ساعة","colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp'),
('s2-jbl-wave-beam', 'سماعة JBL Wave Beam', 'JBL', (select id from cat), 'new', '4G', 39, null, 25, 'سماعة JBL Wave Beam — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 30 ساعة","colors":"رمادي"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp'),
('s2-anker-soundcore-life-q30', 'سماعة Anker Soundcore Life Q30', 'Anker', (select id from cat), 'new', '4G', 79, null, 30, 'سماعة Anker Soundcore Life Q30 — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 24 ساعة","colors":"أبيض"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp'),
('s2-soundcore-liberty-4-nc', 'سماعة Soundcore Liberty 4 NC', 'Anker', (select id from cat), 'new', '4G', 89, null, 10, 'سماعة Soundcore Liberty 4 NC — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 12 ساعة","colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp'),
('s2-xiaomi-redmi-buds-6', 'سماعة Xiaomi Redmi Buds 6', 'Xiaomi', (select id from cat), 'new', '4G', 29, null, 15, 'سماعة Xiaomi Redmi Buds 6 — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 40 ساعة","colors":"رمادي"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp'),
('s2-realme-buds-t300', 'سماعة realme Buds T300', 'Realme', (select id from cat), 'new', '4G', 29, null, 20, 'سماعة realme Buds T300 — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 30 ساعة","colors":"أبيض"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp'),
('s2-oneplus-nord-buds-2r', 'سماعة OnePlus Nord Buds 2r', 'OnePlus', (select id from cat), 'new', '4G', 29, null, 25, 'سماعة OnePlus Nord Buds 2r — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 24 ساعة","colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-homepod-mini-cosmic-grey/thumbnail.webp'),
('s2-honor-earbuds-x5', 'سماعة Honor Earbuds X5', 'Honor', (select id from cat), 'new', '4G', 25, null, 30, 'سماعة Honor Earbuds X5 — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 12 ساعة","colors":"رمادي"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/beats-flex-wireless-earphones/thumbnail.webp'),
('s2-jbl-flip-6', 'مكبر صوت JBL Flip 6', 'JBL', (select id from cat), 'new', '4G', 99, null, 10, 'مكبر صوت JBL Flip 6 — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 40 ساعة","colors":"أبيض"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp'),
('s2-anker-soundcore-motion-boom', 'مكبر صوت Anker Soundcore Motion Boom', 'Anker', (select id from cat), 'new', '4G', 89, null, 15, 'مكبر صوت Anker Soundcore Motion Boom — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 30 ساعة","colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods/thumbnail.webp'),
('s2-jbl-go-4', 'مكبر صوت JBL Go 4', 'JBL', (select id from cat), 'new', '4G', 39, null, 20, 'مكبر صوت JBL Go 4 — صوت نقي وتصميم مريح، أصلية 100% بضمان المتجر.', '{"battery":"حتى 24 ساعة","colors":"رمادي"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpods-max-silver/thumbnail.webp')
on conflict (slug) do nothing;


with cat as (select id from public.categories where slug='chargers')
insert into public.products (slug, name, brand, category_id, condition, network, price, old_price, stock, description, specs, main_image) values
('s2-anker-nano-30w-gan', 'شاحن Anker Nano 30W GaN', 'Anker', (select id from cat), 'new', '4G', 19, null, 10, 'شاحن Anker Nano 30W GaN — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أبيض"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp'),
('s2-baseus-gan5-65w', 'شاحن Baseus GaN5 65W', 'Baseus', (select id from cat), 'new', '4G', 25, null, 15, 'شاحن Baseus GaN5 65W — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp'),
('s2-ugreen-100w-gan', 'شاحن Ugreen 100W GaN', 'Ugreen', (select id from cat), 'new', '4G', 39, null, 20, 'شاحن Ugreen 100W GaN — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أبيض"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp'),
('s2-samsung-25w', 'شاحن Samsung أصلي 25W', 'Samsung', (select id from cat), 'new', '4G', 13, null, 25, 'شاحن Samsung أصلي 25W — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp'),
('s2-xiaomi-33w', 'شاحن Xiaomi 33W', 'Xiaomi', (select id from cat), 'new', '4G', 11, null, 30, 'شاحن Xiaomi 33W — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أبيض"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp'),
('s2-huawei-supercharge-66w', 'شاحن Huawei SuperCharge 66W', 'Huawei', (select id from cat), 'new', '4G', 19, null, 10, 'شاحن Huawei SuperCharge 66W — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp'),
('s2-anker-45w', 'شاحن سيارة Anker 45W', 'Anker', (select id from cat), 'new', '4G', 12, null, 15, 'شاحن سيارة Anker 45W — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أبيض"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp'),
('s2-magsafe', 'قاعدة شحن MagSafe', 'Apple', (select id from cat), 'new', '4G', 35, null, 20, 'قاعدة شحن MagSafe — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp'),
('s2-anker-usb-c-100w-1', 'كابل Anker USB-C 100W 1م', 'Anker', (select id from cat), 'new', '4G', 12, null, 25, 'كابل Anker USB-C 100W 1م — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أبيض"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp'),
('s2-apple-lightning-1', 'كابل Apple Lightning أصلي 1م', 'Apple', (select id from cat), 'new', '4G', 10, null, 30, 'كابل Apple Lightning أصلي 1م — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp'),
('s2-2-chargers-10', 'كابل مقوى نايلون 2م', 'Baseus', (select id from cat), 'new', '4G', 7, null, 10, 'كابل مقوى نايلون 2م — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أبيض"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp'),
('s2--chargers-11', 'حامل شحن لاسلكي للسيارة', 'Baseus', (select id from cat), 'new', '4G', 22, null, 15, 'حامل شحن لاسلكي للسيارة — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp'),
('s2-anker-20000mah', 'باور بانك Anker 20000mAh', 'Anker', (select id from cat), 'new', '4G', 39, null, 20, 'باور بانك Anker 20000mAh — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أبيض"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-airpower-wireless-charger/thumbnail.webp'),
('s2-baseus-10000mah', 'باور بانك Baseus 10000mAh', 'Baseus', (select id from cat), 'new', '4G', 19, null, 25, 'باور بانك Baseus 10000mAh — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp'),
('s2-5000mah', 'باور بانك مغناطيسي 5000mAh', 'Anker', (select id from cat), 'new', '4G', 29, null, 30, 'باور بانك مغناطيسي 5000mAh — شحن سريع وآمن بجودة أصلية وضمان المتجر.', '{"colors":"أبيض"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-magsafe-battery-pack/thumbnail.webp')
on conflict (slug) do nothing;


with cat as (select id from public.categories where slug='cases')
insert into public.products (slug, name, brand, category_id, condition, network, price, old_price, stock, description, specs, main_image) values
('s2-iphone-16-pro-max', 'كفر شفاف iPhone 16 Pro Max', 'Mobily Bro', (select id from cat), 'new', '4G', 9, null, 10, 'كفر شفاف iPhone 16 Pro Max — حماية أنيقة تناسب جهازك بشكل مثالي وتحافظ عليه من الخدوش والسقوط.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'),
('s2-iphone-15', 'كفر سيليكون iPhone 15', 'Apple', (select id from cat), 'new', '4G', 12, null, 15, 'كفر سيليكون iPhone 15 — حماية أنيقة تناسب جهازك بشكل مثالي وتحافظ عليه من الخدوش والسقوط.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'),
('s2-galaxy-s25-ultra', 'كفر Galaxy S25 Ultra مقاوم للصدمات', 'Mobily Bro', (select id from cat), 'new', '4G', 12, null, 20, 'كفر Galaxy S25 Ultra مقاوم للصدمات — حماية أنيقة تناسب جهازك بشكل مثالي وتحافظ عليه من الخدوش والسقوط.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'),
('s2-galaxy-a56', 'كفر Galaxy A56', 'Mobily Bro', (select id from cat), 'new', '4G', 8, null, 25, 'كفر Galaxy A56 — حماية أنيقة تناسب جهازك بشكل مثالي وتحافظ عليه من الخدوش والسقوط.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'),
('s2-redmi-note-14', 'كفر Redmi Note 14', 'Mobily Bro', (select id from cat), 'new', '4G', 7, null, 30, 'كفر Redmi Note 14 — حماية أنيقة تناسب جهازك بشكل مثالي وتحافظ عليه من الخدوش والسقوط.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'),
('s2-iphone-16', 'كفر محفظة جلد iPhone 16', 'Apple', (select id from cat), 'new', '4G', 19, null, 10, 'كفر محفظة جلد iPhone 16 — حماية أنيقة تناسب جهازك بشكل مثالي وتحافظ عليه من الخدوش والسقوط.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'),
('s2-9h-iphone-16', 'زجاج 9H لـ iPhone 16', 'Mobily Bro', (select id from cat), 'new', '4G', 6, null, 15, 'زجاج 9H لـ iPhone 16 — حماية أنيقة تناسب جهازك بشكل مثالي وتحافظ عليه من الخدوش والسقوط.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'),
('s2-9h-galaxy-s25', 'زجاج 9H لـ Galaxy S25', 'Mobily Bro', (select id from cat), 'new', '4G', 6, null, 20, 'زجاج 9H لـ Galaxy S25 — حماية أنيقة تناسب جهازك بشكل مثالي وتحافظ عليه من الخدوش والسقوط.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'),
('s2--cases-8', 'حماية عدسة الكاميرا', 'Mobily Bro', (select id from cat), 'new', '4G', 4, null, 25, 'حماية عدسة الكاميرا — حماية أنيقة تناسب جهازك بشكل مثالي وتحافظ عليه من الخدوش والسقوط.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'),
('s2--cases-9', 'حافظة جيب جلدية', 'Mobily Bro', (select id from cat), 'new', '4G', 9, null, 30, 'حافظة جيب جلدية — حماية أنيقة تناسب جهازك بشكل مثالي وتحافظ عليه من الخدوش والسقوط.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'),
('s2-apple-watch', 'سوار Apple Watch رياضي', 'Apple', (select id from cat), 'new', '4G', 8, null, 10, 'سوار Apple Watch رياضي — حماية أنيقة تناسب جهازك بشكل مثالي وتحافظ عليه من الخدوش والسقوط.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp'),
('s2--cases-11', 'حامل تابلت للسرير', 'Mobily Bro', (select id from cat), 'new', '4G', 14, null, 15, 'حامل تابلت للسرير — حماية أنيقة تناسب جهازك بشكل مثالي وتحافظ عليه من الخدوش والسقوط.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/iphone-12-silicone-case-with-magsafe-plum/thumbnail.webp')
on conflict (slug) do nothing;


with cat as (select id from public.categories where slug='watches')
insert into public.products (slug, name, brand, category_id, condition, network, price, old_price, stock, description, specs, main_image) values
('s2-apple-watch-se-3-gps-40mm', 'Apple Watch SE 3 GPS 40mm', 'Apple', (select id from cat), 'new', '4G', 229, null, 10, 'Apple Watch SE 3 GPS 40mm — تتبع صحتك ولياقتك بأسلوب أنيق، أصلية بضمان المتجر.', '{"battery":"18 ساعة","os":"watchOS","colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-watch-series-4-gold/thumbnail.webp'),
('s2-apple-watch-ultra-2-49mm', 'Apple Watch Ultra 2 49mm', 'Apple', (select id from cat), 'new', '4G', 749, null, 15, 'Apple Watch Ultra 2 49mm — تتبع صحتك ولياقتك بأسلوب أنيق، أصلية بضمان المتجر.', '{"battery":"حتى 14 يوم","os":"Wear OS","colors":"فضي"}', 'https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/thumbnail.webp'),
('s2-galaxy-watch7-44mm', 'Galaxy Watch7 44mm', 'Samsung', (select id from cat), 'new', '4G', 299, null, 20, 'Galaxy Watch7 44mm — تتبع صحتك ولياقتك بأسلوب أنيق، أصلية بضمان المتجر.', '{"battery":"حتى 10 أيام","os":"Zepp OS","colors":"ذهبي"}', 'https://cdn.dummyjson.com/product-images/mens-watches/longines-master-collection/thumbnail.webp'),
('s2-galaxy-watch-fe-40mm', 'Galaxy Watch FE 40mm', 'Samsung', (select id from cat), 'new', '4G', 179, null, 25, 'Galaxy Watch FE 40mm — تتبع صحتك ولياقتك بأسلوب أنيق، أصلية بضمان المتجر.', '{"battery":"حتى 36 ساعة","os":"MagicOS","colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-date-black-dial/thumbnail.webp'),
('s2-xiaomi-watch-s4', 'Xiaomi Watch S4', 'Xiaomi', (select id from cat), 'new', '4G', 119, null, 30, 'Xiaomi Watch S4 — تتبع صحتك ولياقتك بأسلوب أنيق، أصلية بضمان المتجر.', '{"battery":"18 ساعة","os":"watchOS","colors":"فضي"}', 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-cellini-moonphase/thumbnail.webp'),
('s2-redmi-watch-5', 'Redmi Watch 5', 'Xiaomi', (select id from cat), 'new', '4G', 49, null, 10, 'Redmi Watch 5 — تتبع صحتك ولياقتك بأسلوب أنيق، أصلية بضمان المتجر.', '{"battery":"حتى 14 يوم","os":"Wear OS","colors":"ذهبي"}', 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-datejust/thumbnail.webp'),
('s2-huawei-watch-gt-5-46mm', 'Huawei Watch GT 5 46mm', 'Huawei', (select id from cat), 'new', '4G', 229, null, 15, 'Huawei Watch GT 5 46mm — تتبع صحتك ولياقتك بأسلوب أنيق، أصلية بضمان المتجر.', '{"battery":"حتى 10 أيام","os":"Zepp OS","colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/mens-watches/rolex-submariner-watch/thumbnail.webp'),
('s2-amazfit-gtr-4', 'Amazfit GTR 4', 'Amazfit', (select id from cat), 'new', '4G', 179, null, 20, 'Amazfit GTR 4 — تتبع صحتك ولياقتك بأسلوب أنيق، أصلية بضمان المتجر.', '{"battery":"حتى 36 ساعة","os":"MagicOS","colors":"فضي"}', 'https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/thumbnail.webp'),
('s2-amazfit-bip-5', 'Amazfit Bip 5', 'Amazfit', (select id from cat), 'new', '4G', 69, null, 25, 'Amazfit Bip 5 — تتبع صحتك ولياقتك بأسلوب أنيق، أصلية بضمان المتجر.', '{"battery":"18 ساعة","os":"watchOS","colors":"ذهبي"}', 'https://cdn.dummyjson.com/product-images/womens-watches/rolex-cellini-moonphase/thumbnail.webp'),
('s2-honor-band-9', 'Honor Band 9', 'Honor', (select id from cat), 'new', '4G', 35, null, 30, 'Honor Band 9 — تتبع صحتك ولياقتك بأسلوب أنيق، أصلية بضمان المتجر.', '{"battery":"حتى 14 يوم","os":"Wear OS","colors":"أسود"}', 'https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/thumbnail.webp')
on conflict (slug) do nothing;


with cat as (select id from public.categories where slug='accessories')
insert into public.products (slug, name, brand, category_id, condition, network, price, old_price, stock, description, specs, main_image) values
('s2--accessories-0', 'حامل موبايل مغناطيسي للسيارة', 'Baseus', (select id from cat), 'new', '4G', 11, null, 10, 'حامل موبايل مغناطيسي للسيارة — إضافة عملية لجهازك بجودة ممتازة وسعر مناسب.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/monopod/thumbnail.webp'),
('s2--accessories-1', 'عصا سيلفي ثلاثية القوائم', 'Mobily Bro', (select id from cat), 'new', '4G', 12, null, 15, 'عصا سيلفي ثلاثية القوائم — إضافة عملية لجهازك بجودة ممتازة وسعر مناسب.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-lamp-with-iphone/thumbnail.webp'),
('s2-10-accessories-2', 'إضاءة حلقة 10 بوصة', 'Mobily Bro', (select id from cat), 'new', '4G', 14, null, 20, 'إضاءة حلقة 10 بوصة — إضافة عملية لجهازك بجودة ممتازة وسعر مناسب.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-stick-monopod/thumbnail.webp'),
('s2--accessories-3', 'حامل حلقة للجوال', 'Mobily Bro', (select id from cat), 'new', '4G', 6, null, 25, 'حامل حلقة للجوال — إضافة عملية لجهازك بجودة ممتازة وسعر مناسب.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/tv-studio-camera-pedestal/thumbnail.webp'),
('s2-otg-type-c', 'مفتاح OTG Type-C', 'Mobily Bro', (select id from cat), 'new', '4G', 5, null, 30, 'مفتاح OTG Type-C — إضافة عملية لجهازك بجودة ممتازة وسعر مناسب.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/monopod/thumbnail.webp'),
('s2-stylus', 'قلم Stylus عالمي للموبايل والتابلت', 'Baseus', (select id from cat), 'new', '4G', 12, null, 10, 'قلم Stylus عالمي للموبايل والتابلت — إضافة عملية لجهازك بجودة ممتازة وسعر مناسب.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-lamp-with-iphone/thumbnail.webp'),
('s2--accessories-6', 'سلسلة هاتف قماشية', 'Mobily Bro', (select id from cat), 'new', '4G', 8, null, 15, 'سلسلة هاتف قماشية — إضافة عملية لجهازك بجودة ممتازة وسعر مناسب.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-stick-monopod/thumbnail.webp'),
('s2--accessories-7', 'حافظة بطاقات خلف الهاتف', 'Mobily Bro', (select id from cat), 'new', '4G', 7, null, 20, 'حافظة بطاقات خلف الهاتف — إضافة عملية لجهازك بجودة ممتازة وسعر مناسب.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/tv-studio-camera-pedestal/thumbnail.webp'),
('s2--accessories-8', 'منظف شاشات وعدسات', 'Mobily Bro', (select id from cat), 'new', '4G', 4, null, 25, 'منظف شاشات وعدسات — إضافة عملية لجهازك بجودة ممتازة وسعر مناسب.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/monopod/thumbnail.webp'),
('s2--accessories-9', 'فرشاة تنظيف منافذ الشحن', 'Mobily Bro', (select id from cat), 'new', '4G', 3, null, 30, 'فرشاة تنظيف منافذ الشحن — إضافة عملية لجهازك بجودة ممتازة وسعر مناسب.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-lamp-with-iphone/thumbnail.webp'),
('s2-sd-type-c', 'محول بطاقات SD عبر Type-C', 'Ugreen', (select id from cat), 'new', '4G', 9, null, 10, 'محول بطاقات SD عبر Type-C — إضافة عملية لجهازك بجودة ممتازة وسعر مناسب.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/selfie-stick-monopod/thumbnail.webp'),
('s2--accessories-11', 'عدسة تصوير ماكرو للجوال', 'Baseus', (select id from cat), 'new', '4G', 15, null, 15, 'عدسة تصوير ماكرو للجوال — إضافة عملية لجهازك بجودة ممتازة وسعر مناسب.', '{}', 'https://cdn.dummyjson.com/product-images/mobile-accessories/tv-studio-camera-pedestal/thumbnail.webp')
on conflict (slug) do nothing;